### ISSUE TITLE
Referral 系统

### ISSUE THREAD

**Issue by lychees** [nekomeowww/cryptohero-bsc-frontend-ng#2]
可参考隔壁 YFV 的实现。。
https://valuedefi.io/?a=0x6465F1250c9fe162602Db83791Fc3Fb202D70a7B

目前的问题：
1. [x] Header 直接通过首页进去
https://ayaka.netlify.app/
Referral 会不出来。。
通过卡片页面访问则可以。。
https://ayaka.netlify.app/item/1

2. [x] https://ayaka.netlify.app/referral?l=MHg2NDY1RjEyNTBjOWZlMTYyNjAyRGI4Mzc5MUZjM0ZiMsSTRDcwYTdC
通过邀请链接进入，应该进入首页，并将邀请人写在 cookie 里，在 buy 的时候写入。

**Comment by nekomeowww** [comment]
Fixed one

**Comment by nekomeowww** [comment]
已完成
